export enum BigModalTitles {
    LEVEL_PROGRESS = 'LEVEL PROGRESS',
    SPECIAL_OFFER = 'SPECIAL OFFER',
    JUST_FOR_YOU_OFFER = 'JUST FOR YOU!',
    HAPPY_OFFER = 'HAPPY OFFER!',
    LUCKY_OFFER = 'LUCKY OFFER!',
}