name: CI

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: npm ci
      - name: check eslint
        run: npm run lint